### ISSUE TITLE
how to find data?

### ISSUE THREAD

**Issue by handesome** [lylamha/pseudotime_comparison_analysis#1]
hi!I want to know where could I find the data that mentioned in your code?Thanks!!!

**Comment by lylamha** [comment]
Unfortunately I don't have access to the data anymore. But I conducted this analysis based on this published article ([DOI: 10.1126/sciimmunol.aal2192](https://doi.org/10.1126/sciimmunol.aal2192). It was part of the supplementary computational methods. Hope that helps!

**Comment by handesome** [comment]
wow, Thank you for the reply. That's important for me.

**Comment by handesome** [comment]
Unfortunately ,I could not find the datasets.Hope someone else could solve the problem.......

**Comment by handesome** [comment]
> Unfortunately I don't have access to the data anymore. But I conducted this analysis based on this published article ([DOI: 10.1126/sciimmunol.aal2192](https://doi.org/10.1126/sciimmunol.aal2192). It was part of the supplementary computational methods. Hope that helps!

could you please help me to find the data, it's important for me.I wanna cry

**Comment by lylamha** [comment]
Sorry, but what is your problem? I can't help you if you don't say where your problem is. The data that was used is referenced. You have to look into the studies and download the files and process it.

**Comment by handesome** [comment]
Thank you for the reply.maybe I miss something.I just could not find the data,I will try other pseudotime comparison way,do you konw some else pseudotime comparison trajectory? Thanks

**Comment by lylamha** [comment]
Maybe try this one: https://doi.org/10.1038/s41587-019-0071-9. They have freely available data and an evaluation pipeline that one can use.
